Introduction:

- AI = Technique which enables machines to mimic human behaviour
- ML = Subset of AI techniques which uses statistical methods to enable machines to improve with experience
- DL = Subset of ML which makes the computation of multi-layer neural networks feasible

Complete End-to-End ML Project
1. Create dataset by web scraping using Bing/Google Image search APIs
2. Feature Extractions
3. Build model
4. Hyperparameter Tuning to achieve high accuracy
5. Model depolyment by building a web App using Streamlit


# Data Gathering

Use bing-image-downloader Python library to scrape the images from the web for the dataset

In [ ]:
#Install bing-image-downloader
!pip install bing-image-downloader
#to get execution time for running each cell
!pip install ipython-autotime
%load_ext autotime

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.3 MB/s eta 0:00:00
time: 428 µs (started: 2023-09-10 12:20:02 +00:00)


In [ ]:
#Create a folder directory called images
!mkdir images

time: 106 ms (started: 2023-09-10 12:20:02 +00:00)


In [ ]:
from bing_image_downloader import downloader
#Download first class of images
downloader.download('pretty sunflower', #query string to be searched
                    limit = 40, # number of images to download
                    output_dir = 'images', # name of output directory to save the images
                    adult_filter_off= True) #enable adult filtration

[%] Downloading Images to /content/images/pretty sunflower


[!!]Indexing page: 1

[%] Indexed 35 Images on Page 1.


[%] Downloading Image #1 from https://www.10wallpaper.com/wallpaper/2560x1440/1802/Pretty_sunflower_flowers_plant_closeup_2560x1440.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://preppywallpapers.com/wp-content/uploads/2019/08/Sunflower-iPhone-Wallpapers.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://s1.picswalls.com/wallpapers/2014/07/17/free-sunflower-wallpaper_110754619_53.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://www.wallpapers13.com/wp-content/uploads/2015/12/Sunflower-Field-Wallpaper-Beautiful-Flowers-Pictures-Sunflower-Field-Wallpaper.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://travelikealocalvt.com/wp-content/uploads/2014/10/sunflower-963x1024.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://preppywallpapers.com/wp-content/uploads/2019/08/Sunflower-iPhone-Wallpaper-6.jp

In [ ]:
#Download second class of images
downloader.download('tesla car', #query string to be searched
                    limit = 40, # number of images to download
                    output_dir = 'images', # name of output directory to save the images
                    adult_filter_off= True) #enable adult filtration

[%] Downloading Images to /content/images/tesla car


[!!]Indexing page: 1

[%] Indexed 35 Images on Page 1.


[%] Downloading Image #1 from https://starrluxurycars.com/wp-content/uploads/2019/01/TESBG.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://www.hdcarwallpapers.com/walls/tesla_roadster_sports_car-wide.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://static1.businessinsider.com/image/57756a308d3eae2d51880517-1920/key fobmp400011612still005.png
[!] Issue getting: http://static1.businessinsider.com/image/57756a308d3eae2d51880517-1920/key fobmp400011612still005.png
[!] Error:: URL can't contain control characters. '/image/57756a308d3eae2d51880517-1920/key fobmp400011612still005.png' (found at least ' ')
[%] Downloading Image #3 from http://4.bp.blogspot.com/-YwNv6zaieOY/UZPHP1EIL6I/AAAAAAAAAus/341bHpb34WU/s1600/tesla+model+s+65.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://cdni.autocarindia.com/ExtraImages/20141013125258_teslamodels

In [ ]:
#Download third class of images
downloader.download('glass of water', #query string to be searched
                    limit = 40, # number of images to download
                    output_dir = 'images', # name of output directory to save the images
                    adult_filter_off= True) #enable adult filtration

[%] Downloading Images to /content/images/glass of water


[!!]Indexing page: 1

[%] Indexed 35 Images on Page 1.


[%] Downloading Image #1 from http://blog.watershed.net/wp-content/uploads/2013/03/water_glass.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://fitnessjockey.com/wp-content/uploads/2017/03/water-glass.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.healthstandnutrition.com/wp-content/uploads/2015/09/glass-of-water.jpg
[!] Issue getting: https://www.healthstandnutrition.com/wp-content/uploads/2015/09/glass-of-water.jpg
[!] Error:: HTTP Error 502: Bad Gateway
[%] Downloading Image #3 from http://openparachute.files.wordpress.com/2012/03/glass-water-3.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://www.dabistro.restaurant/wp-content/uploads/2014/09/glass-of-water.png
[%] File Downloaded !

[%] Downloading Image #5 from https://p0.pxfuel.com/preview/243/121/215/glass-of-water-water-glass-thirst.jpg
[%] File Downloaded !

[%]

# Preprocessing

In [ ]:
#Import packages

import os # operating system needed becuase navigating betwwen different folders
import matplotlib.pyplot as plt # to display image
import numpy as np # for numerical computing
from skimage.io import imread # for reading images
from skimage.transform import resize_local_mean # for resizing all images to be uniform (the same size) as required for ML
from skimage.transform import resize


time: 1.26 s (started: 2023-09-10 12:21:33 +00:00)


In [ ]:
#Need to flatten the 2D matrix of images into a 1D array input
#Convert 2D matrix to 1D vector using the flatten method

#Create empty lists to store data
target = [] #output classification
images = [] # cannot be passed to ML model beucase 2D matrix
flat_data = [] #data to be passed to ML model as 1D array

datadir = '/content/images'
categories =['pretty sunflower', 'tesla car', 'glass of water' ]

#iterate through all data
for category in categories:
  class_num = categories.index(category) # label encoding the values to represent the classes as numbers 0,1,2
  path = os.path.join(datadir,category) # create path to use all images
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img)) #values of all images

    #Resize images
    img_resized = resize(img_array,(150, 150,3 )) # Normalizes the values to be between 0 and 1
    #Flatten images
    flat_data.append(img_resized.flatten())

    images.append(img_resized)
    target.append(class_num)

#Convert to numpy arrays
flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)
#flat_data[0]

time: 2min 32s (started: 2023-09-10 12:21:34 +00:00)


Train-Test Split

In [ ]:
#Train - Test Split Data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(flat_data,
                                                    target,
                                                    test_size=0.3,
                                                    random_state=50)

time: 268 ms (started: 2023-09-10 12:24:07 +00:00)


- Using SVM Classification Model (Support vector machines) - Supervised learning method
- Use GridSearchCV to select the best model parameters

SVC Parameters for tuning the model:
- Regularisation
- Kernel
- Gamma


In [ ]:
#Usign GridSearch CV to select the best parameters
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [{'C':[1,10,100,1000],'kernel':['linear']},
              {'C':[1,10,100,1000],'kernel':['rbf'], 'gamma':[0.001, 0.0001]}]

svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid)
# fit training data to model
clf.fit(x_train, y_train)

GridSearchCV(estimator=SVC(probability=True),
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}])

time: 1min 25s (started: 2023-09-10 12:24:07 +00:00)


In [ ]:
#Fit to test data
y_pred = clf.predict(x_test)
y_pred

array([1, 0, 2, 0, 2, 0, 1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 2, 1, 2, 1, 1, 0, 0, 2, 1, 0, 1, 2])

time: 274 ms (started: 2023-09-10 12:25:32 +00:00)


In [ ]:
y_test

array([1, 0, 2, 0, 2, 0, 1, 2, 2, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 2])

time: 5.58 ms (started: 2023-09-10 12:25:33 +00:00)


In [ ]:
#Evaluate model perfomrance
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_pred, y_test)

0.8333333333333334

time: 7.82 ms (started: 2023-09-10 12:25:33 +00:00)


In [ ]:
confusion_matrix(y_pred, y_test)

array([[13,  0,  0],
       [ 1, 10,  4],
       [ 0,  1,  7]])

time: 5.4 ms (started: 2023-09-10 12:25:33 +00:00)


Save model using Pickle Library

In [ ]:
import pickle
pickle.dump(clf, open('img_model.p', 'wb')) #Creates file called 'img_model.p' where model is saved

time: 72.3 ms (started: 2023-09-10 12:25:33 +00:00)


In [ ]:
model = pickle.load(open('img_model.p', 'rb'))

time: 11.4 ms (started: 2023-09-10 12:25:33 +00:00)


In [ ]:
#Testing a brand new image

#flat_data = []
#url = input('Enter your URL') #Prompt message to User
#img = imread(url) #read url
#img_resized = resize(img,(150,150,3))#resize image
#flat_data.append(img_resized.flatten())#flatten image
#flat_data = np.array(flat_data)

#print(img.shape)
#plt.imshow(img_resized)
#y_out = model.predict(flat_data)
#y_out = categories[y_out[0]]
#print(f'Predicted Output: {y_out}')

time: 359 µs (started: 2023-09-10 12:25:33 +00:00)


# Model Deployment

Forms of Deployment:
1. Web Page - HTML/CSS/JS - Flask/Djanjo
2. Web App - Streamlit/Dash
3. Mobile App - Kotlin/Java

Here Using Streamlit application to deploy model through a web app

In [ ]:
!pip install streamlit
!pip install pyngrok
from pyngrok import ngrok

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 15.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 kB 14.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.8/188.8 kB 19.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 36.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 5.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 23.0 MB/s eta 0:00:00
  Attempting uninstall: tzlocal
    Found existing installation: tzlocal 5.0.1
    Uninstalling tzlocal-5.0.1:
      Successfully uninstalled tzlocal-5.0.1
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 681.2/681.2 kB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-6.0.0-py3-none-any.whl size=19867 sha256=d1af677ddb98013d24c982c32ff9ef5b4ca111132575e78ad383af1f20792d1e
  Stored 

In [ ]:
# Create a Streamlit app file
%%writefile app.py
import streamlit as st
import numpy as np
from skimage.io import imread
from skimage.transform import resize
import pickle
from PIL import Image

def main():
    st.title('Image Classifier Using Machine Learning')
    st.text('Upload the Image')
    #Streamlit app code goes here
    uploaded_file = st.file_uploader('Choose an image...', type='jpg')
    model = pickle.load(open('img_model.p', 'rb'))
    if uploaded_file is not None:
      img = Image.open(uploaded_file)
      st.image(img, caption='Uploaded Image')
      if st.button('Predict'):
        categories =['pretty sunflower', 'tesla car', 'glass of water' ]
        #Model prediction code
        st.write('Result:')
        flat_data = []
        img = np.array(img)
        img_resized = resize(img,(150,150,3))
        flat_data.append(img_resized.flatten())
        flat_data = np.array(flat_data)
        y_out = model.predict(flat_data)
        y_out = categories[y_out[0]]
        st.title(f'Prediction: {y_out}')
        #Get percentage of prediction
        q = model.predict_proba(flat_data)
        for index, item in enumerate(categories):
          st.write(f'{item} : {q[0][index]*100:.4f}%')
if __name__ == '__main__':
    main()

Writing app.py
time: 2.96 ms (started: 2023-09-10 12:25:50 +00:00)


In [ ]:
ngrok.set_auth_token('2V1SOWqyrGFyBd6mpaFLcYoRIRt_4L8oqBQ8uJ5i83ZbVPf4n')

time: 987 ms (started: 2023-09-10 12:25:50 +00:00)


In [ ]:
# Run the Streamlit app in the background
#!nohup streamlit run app.py &
!nohup streamlit run --server.port 80 app.py &
# Use ngrok to expose the app to the internet
from pyngrok import ngrok
url = ngrok.connect(80)
print(url)

nohup: appending output to 'nohup.out'


NgrokTunnel: "https://d5d0-35-196-233-232.ngrok-free.app" -> "http://localhost:80"
time: 347 ms (started: 2023-09-10 12:25:51 +00:00)
